### ISSUE TITLE
mainTemplate.gradle میخوام بیلد بگیرم یه ارور مربوط به این فایل دریافت میکنم

### ISSUE THREAD

**Issue by MasihGd** [tapsellorg/TapsellPlusSDK-UnitySample2019#12]
<div dir='rtl'>

**شرح باگ در پلاگین**:

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

mainTemplate.gradle file is using the old aaptOptions noCompress property definition which does not include types defined by unityStreamingAssets constant.

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by MortezaNedaei** [comment]
قطعه کد زیر رو به فایل `mainTemplate.gradle` اضافه کنید:
```gradle
 aaptOptions {
         noCompress = ['.ress', '.resource', '.obb'] + unityStreamingAssets.tokenize(', ')
         ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
     }
```

**Comment by mahdi-malv** [comment]
Feel free to re-open if the problem still exists
