### ISSUE TITLE
کرش بازی هنگام شروع نمایش تبلیغ ویدیو جایزه ای 

### ISSUE THREAD

**Issue by am1rzagro** [tapsellorg/TapsellPlusSDK-UnitySample2019#14]
<div dir='rtl'>

سلام 
بعد از پیاده سازی اس دی کی تپسل پلاس  متوجه شدم که در برخی از قسمت های بازی که بیشتر در قسمت های سنگین تر اون هست بعد از درخواست نمایش تبلیغ بازی کرش میکنه یا صفحه سیاه میمونه و تبلیغ لود نمیشه ، هیچ ارور خاصی هم مشاهده نمیشه ، 
در برخی موارد بعد ااز چند بار نمایش تبلیغ این اتفاق میافته 
ممنون میشم راهنمایی بفرمایید. 

ورژن یونیتی 2020.3.2

</div>

**Comment by MortezaNedaei** [comment]
سلام
بدون لاگ، نمیشه مشکل رو فهمید. میتونید داخل یونیتی از `Android Logcat` استفاده کنید. اونجا یه فیلتر روی `tapsell` بذارید ببینید چه لاگ هایی داره از کتابخانه ارسال میشه.
