### ISSUE TITLE
🐛  باگ: 

### ISSUE THREAD

**Issue by hamidrezal** [tapsellorg/TapsellPlusSDK-UnitySample2019#15]
<div dir='rtl'>

**شرح باگ در پلاگین**:
موقع گرفتن خروجی در نسخه ی 2021.3.5f1  یک پیغام به عنوان gradel build failes. see the console for details نمایش داده میشه

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

CommandInvokationFailure: Gradle build failed. 
C:\Program Files\Java\jdk1.8.0_77\bin\java.exe -classpath "F:\Program File\Unity\2021.3.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-6.1.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by MortezaNedaei** [comment]
سلام وقت بخیر
لطفا مطمئن بشید در حین خروجی گرفتن از فیلترشکن استفاده می کنید
همچنین خطاهای دیگه ای که در کنسول مشاهده می شه رو هم بفرستید چون علت build failedدر خطای بالا مشخص نیست ( می تونید روی تب Console راست کلیک کنید و Open Editor Log رو انتخاب کنید )

**Comment by MortezaNedaei** [comment]
به نظر میاد مشکل حل شده اگر همچنان وجود داشت، Issue رو دوباره باز کنید.

**Comment by MortezaNedaei** [comment]
به نظر میاد مشکل حل شده اگر همچنان وجود داشت، Issue رو دوباره باز کنید.

**Comment by hamidrezal** [comment]
سلام وقت بخیر بعد از بررسی خطاها متوجه شدم مربوط به فعال سازی برای اندروید x  هست و احتملا شیوه ای که داخل مستندات نوشته شده در  نسخه ی جدید یونیتی فعال نمیشه و به همراه اون باید این دستور ها هم داخل فایل Manifastوارد بشن
android.useAndroidX=true
android.enableJetifier=true
