### ISSUE TITLE
عدم  تشخیص result  در کد های تپسل

### ISSUE THREAD

**Issue by mry1383** [tapsellorg/TapsellPlusSDK-UnitySample2019#17]
TapsellPlusSDK
به تمامی عبارت های (result/Result) در کد ها ارور داده است.

Assets\TapsellPlus\TapsellPlus.cs(223,29): error CS1061: 'UnityWebRequest' does not contain a definition for 'result' and no accessible extension method 'result' accepting a first argument of type 'UnityWebRequest' could be found (are you missing a using directive or an assembly reference?)
.......

**Comment by QM4RS** [comment]
دقیقا منم الان همین مشکل رو دارم
یونیتی 2019.4.10 استفاده میکنم.

**Comment by MortezaNedaei** [comment]
Hello there!
You should upgrade the Unity editor version to 2020 or higher.
Let me know if it is fixed after doing so.

**Comment by MortezaNedaei** [comment]
سلام و وقت بخیر
لطفا ورژن Unity Editor را به 2020 و یا بالاتر ارتقا دهید.
