### ISSUE TITLE
🐛  باگ: مشکل خروجی گرفتن اندروید و خطای Duplicate class

### ISSUE THREAD

**Issue by fazelit** [tapsellorg/TapsellPlusSDK-UnitySample2019#38]
<div dir='rtl'>

**شرح باگ در پلاگین**:
موقع خروجی اندروید خطای زیر می دهد:

**متن کامل خطا یا لاگ مرتبط به طور کامل**:

`FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class _COROUTINE.ArtificialStackFrames found in modules jetified-kotlinx-coroutines-core-jvm-1.7.1 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.1) and jetified-org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1 (org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1.jar)
     Duplicate class _COROUTINE.CoroutineDebuggingKt found in modules jetified-kotlinx-coroutines-core-jvm-1.7.1 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.1) and jetified-org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1 (org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1.jar)
     Duplicate class _COROUTINE._BOUNDARY found in modules jetified-kotlinx-coroutines-core-jvm-1.7.1 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.1) and jetified-org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1 (org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1.jar)
     Duplicate class _COROUTINE._CREATION found in modules jetified-kotlinx-coroutines-core-jvm-1.7.1 (org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.7.1) and jetified-org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1 (org.jetbrains.kotlinx.kotlinx-coroutines-core-jvm-1.7.1.jar)
     Duplicate class android.support.customtabs.ICustomTabsCallback found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.ICustomTabsCallback$Default found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.ICustomTabsCallback$Stub found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.ICustomTabsCallback$Stub$Proxy found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.ICustomTabsService found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.ICustomTabsService$Default found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.ICustomTabsService$Stub found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.ICustomTabsService$Stub$Proxy found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.IPostMessageService found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.IPostMessageService$Default found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.IPostMessageService$Stub found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.IPostMessageService$Stub$Proxy found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.trusted.ITrustedWebActivityCallback found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.trusted.ITrustedWebActivityCallback$Default found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.trusted.ITrustedWebActivityCallback$Stub found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.trusted.ITrustedWebActivityCallback$Stub$Proxy found in modules browser-1.4.0-runtime (androidx.browser:browser:1.4.0) and jetified-androidx.browser.browser-1.4.0-runtime (:androidx.browser.browser-1.4.0:)
     Duplicate class android.support.customtabs.trust`

**نحوه‌ی تولید مجدد آن توسط تیم توسعه**:

**پکیج نیم برنامه‌**: ``

**اطلاعات اضافی که به حل مشکل کمک می‌کنند**:  

</div>

**Comment by MortezaNedaei** [comment]
از این پکیج تپسل استفاده و مجدد تست کنید
https://github.com/tapsellorg/TapsellPlusSDK-UnityPlugin/releases/tag/v2.2.6

**Comment by fazelit** [comment]
> از این پکیج تپسل استفاده و مجدد تست کنید https://github.com/tapsellorg/TapsellPlusSDK-UnityPlugin/releases/tag/v2.2.6

با تشکر از شما ولی با این پکیج هم درست نشد.
مثل اینکه باید minSDK رو روی 24 تنظیم می کردم که دیگه درست شد.
