### ISSUE TITLE
🐛  باگ: 

### ISSUE THREAD

**Issue by piranism** [tapsellorg/TapsellPlusSDK-UnitySample2019#7]
<div dir='rtl'>

سلام  من از ورژن رایگان 2020.3.32f1 استفاده می کنم
زمان اضافه کردن Unity به روش Gradle خطا هایی در کد شناسایی می شود مانند :
Assets\TapsellPlus\TapsellPlus.cs(223,21): warning CS0618: 'UnityWebRequest.isNetworkError' is obsolete: 'UnityWebRequest.isNetworkError is deprecated. Use (UnityWebRequest.result == UnityWebRequest.Result.ConnectionError) instead.'

زمان بیلد کردن هم 5 تا ارور داده می شود

/////////////////////////////////////////////////////////////////////////////////

> Configure project :launcher
WARNING: The option setting 'android.enableR8=false' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

/////////////////////////////////////////////////////////////////////////////////

* What went wrong:
Could not determine the dependencies of task ':launcher:lintVitalRelease'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.fragment:fragment:1.0.0, androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.versionedparcelable:versionedparcelable:1.1.0, androidx.core:core:1.2.0, androidx.customview:customview:1.0.0, androidx.swiperefreshlayout:swiperefreshlayout:1.0.0, androidx.interpolator:interpolator:1.0.0, androidx.loader:loader:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.viewpager:viewpager:1.0.0, androidx.collection:collection:1.0.0, androidx.exifinterface:exifinterface:1.2.0, androidx.localbroadcastmanager:localbroadcastmanager:1.0.0, androidx.lifecycle:lifecycle-common:2.0.0, androidx.arch.core:core-common:2.0.0, androidx.annotation:annotation:1.1.0, androidx.legacy:legacy-support-core-ui:1.0.0, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.lifecycle:lifecycle-viewmodel:2.0.0, androidx.lifecycle:lifecycle-livedata-core:2.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.documentfile:documentfile:1.0.0, androidx.vectordrawable:vectordrawable-animated:1.0.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.vectordrawable:vectordrawable:1.0.0, androidx.lifecycle:lifecycle-runtime:2.0.0, androidx.coordinatorlayout:coordinatorlayout:1.0.0, androidx.asynclayoutinflater:asynclayoutinflater:1.0.0, androidx.print:print:1.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

/////////////////////////////////////////////////////////////////////////////////

Build completed with a result of 'Failed' in 121 seconds (121298 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

/////////////////////////////////////////////////////////////////////////////////

UnityEditor.BuildPlayerWindow+BuildMethodException: 4 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ca] in <294703faec74477f8b275446429fba82>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <294703faec74477f8b275446429fba82>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

</div>

**Comment by mahdi-malv** [comment]
سلام
نسخه‌ی آخر تپسل پلاس از UnityWebRequest جدید استفاده میکنه که deprecation warningها رو نداره
در مورد AndroidX (اروری که داره) duplicate این خطا هست: https://github.com/tapsellorg/TapsellPlusSDK-UnitySample2020/issues/7
